declare const _default: {
    validateComposedSchemas: typeof validateComposedSchemas;
    validateNestedSchemas: typeof validateNestedSchemas;
    validateSubschemas: typeof validateSubschemas;
    getNodes: (context: object) => object;
    getResolvedSpec: (context: object) => object;
    getUnresolvedSpec: (context: object) => object;
    isObject: typeof isObject;
    schemaHasConstraint: typeof schemaHasConstraint;
    schemaHasProperty: typeof schemaHasProperty;
    schemaLooselyHasConstraint: typeof schemaLooselyHasConstraint;
    schemaRequiresProperty: typeof schemaRequiresProperty;
    SchemaType: {
        ARRAY: symbol;
        BINARY: symbol;
        BOOLEAN: symbol;
        BYTE: symbol;
        DATE: symbol;
        DATE_TIME: symbol;
        DOUBLE: symbol;
        ENUMERATION: symbol;
        FLOAT: symbol;
        INT32: symbol;
        INT64: symbol;
        INTEGER: symbol;
        NUMBER: symbol;
        OBJECT: symbol;
        STRING: symbol;
        UNKNOWN: symbol;
    };
    getSchemaType: (schema: object) => symbol;
    isArraySchema: (schema: object) => boolean;
    isBinarySchema: (schema: object) => boolean;
    isBooleanSchema: (schema: object) => boolean;
    isByteSchema: (schema: object) => boolean;
    isDateSchema: (schema: object) => boolean;
    isDateTimeSchema: (schema: object) => boolean;
    isDoubleSchema: (schema: object) => boolean;
    isEnumerationSchema: (schema: object) => boolean;
    isFloatSchema: (schema: object) => boolean;
    isInt32Schema: (schema: object) => boolean;
    isInt64Schema: (schema: object) => boolean;
    isIntegerSchema: (schema: object) => boolean;
    isNumberSchema: (schema: object) => boolean;
    isObjectSchema: (schema: object) => boolean;
    isPrimitiveSchema: (schema: object) => boolean;
    isStringSchema: (schema: object) => boolean;
    schemaIsOfType: (schema: object, type: string) => boolean;
    collectFromComposedSchemas: typeof collectFromComposedSchemas;
    getExamplesForSchema: typeof getExamplesForSchema;
    getPropertyNamesForSchema: typeof getPropertyNamesForSchema;
};
export default _default;
import validateComposedSchemas from './validate-composed-schemas.js';
import validateNestedSchemas from './validate-nested-schemas.js';
import validateSubschemas from './validate-subschemas.js';
import isObject from './is-object.js';
import schemaHasConstraint from './schema-has-constraint.js';
import schemaHasProperty from './schema-has-property.js';
import schemaLooselyHasConstraint from './schema-loosely-has-constraint.js';
import schemaRequiresProperty from './schema-requires-property.js';
import collectFromComposedSchemas from './collect-from-composed-schemas.js';
import getExamplesForSchema from './get-examples-for-schema.js';
import getPropertyNamesForSchema from './get-property-names-for-schema.js';
//# sourceMappingURL=index.d.ts.map