declare const _default: {
    validateComposedSchemas: typeof import("./validate-composed-schemas").default;
    validateNestedSchemas: typeof import("./validate-nested-schemas").default;
    validateSubschemas: typeof import("./validate-subschemas").default;
    getNodes: (context: object) => object;
    getResolvedSpec: (context: object) => object;
    getUnresolvedSpec: (context: object) => object;
    isObject: typeof import("./is-object").default;
    schemaHasConstraint: typeof import("./schema-has-constraint").default;
    schemaHasProperty: typeof import("./schema-has-property").default;
    schemaLooselyHasConstraint: typeof import("./schema-loosely-has-constraint").default;
    schemaRequiresProperty: typeof import("./schema-requires-property").default;
    SchemaType: {
        ARRAY: symbol;
        BINARY: symbol;
        BOOLEAN: symbol;
        BYTE: symbol;
        DATE: symbol;
        DATE_TIME: symbol;
        DOUBLE: symbol;
        ENUMERATION: symbol;
        FLOAT: symbol;
        INT32: symbol;
        INT64: symbol;
        INTEGER: symbol;
        NUMBER: symbol;
        OBJECT: symbol;
        STRING: symbol;
        UNKNOWN: symbol;
    };
    getSchemaType: (schema: object) => symbol;
    isArraySchema: (schema: object) => boolean;
    isBinarySchema: (schema: object) => boolean;
    isBooleanSchema: (schema: object) => boolean;
    isByteSchema: (schema: object) => boolean;
    isDateSchema: (schema: object) => boolean;
    isDateTimeSchema: (schema: object) => boolean;
    isDoubleSchema: (schema: object) => boolean;
    isEnumerationSchema: (schema: object) => boolean;
    isFloatSchema: (schema: object) => boolean;
    isInt32Schema: (schema: object) => boolean;
    isInt64Schema: (schema: object) => boolean;
    isIntegerSchema: (schema: object) => boolean;
    isNumberSchema: (schema: object) => boolean;
    isObjectSchema: (schema: object) => boolean;
    isPrimitiveSchema: (schema: object) => boolean;
    isStringSchema: (schema: object) => boolean;
    schemaIsOfType: (schema: object, type: string) => boolean;
    collectFromComposedSchemas: typeof import("./collect-from-composed-schemas").default;
    getExamplesForSchema: typeof import("./get-examples-for-schema");
    getPropertyNamesForSchema: typeof import("./get-property-names-for-schema");
};
export default _default;
//# sourceMappingURL=index.d.ts.map