declare const _default: {
    collections: {
        operations: string[];
        parameters: string[];
        patchOperations: string[];
        paths: string[];
        requestBodySchemas: string[];
        responseSchemas: string[];
        schemas: string[];
        securitySchemes: string[];
        unresolvedRequestBodySchemas: string[];
        unresolvedResponseSchemas: string[];
        unresolvedSchemas: string[];
    };
    validateComposedSchemas: typeof import("./utils/validate-composed-schemas.js").default;
    validateNestedSchemas: typeof import("./utils/validate-nested-schemas.js").default;
    validateSubschemas: typeof import("./utils/validate-subschemas.js").default;
    getNodes: (context: object) => object;
    getResolvedSpec: (context: object) => object;
    getUnresolvedSpec: (context: object) => object;
    isObject: typeof import("./utils/is-object.js").default;
    schemaHasConstraint: typeof import("./utils/schema-has-constraint.js").default;
    schemaHasProperty: typeof import("./utils/schema-has-property.js").default;
    schemaLooselyHasConstraint: typeof import("./utils/schema-loosely-has-constraint.js").default;
    schemaRequiresProperty: typeof import("./utils/schema-requires-property.js").default;
    SchemaType: {
        ARRAY: symbol;
        BINARY: symbol;
        BOOLEAN: symbol;
        BYTE: symbol;
        DATE: symbol;
        DATE_TIME: symbol;
        DOUBLE: symbol;
        ENUMERATION: symbol;
        FLOAT: symbol;
        INT32: symbol;
        INT64: symbol;
        INTEGER: symbol;
        NUMBER: symbol;
        OBJECT: symbol;
        STRING: symbol;
        UNKNOWN: symbol;
    };
    getSchemaType: (schema: object) => symbol;
    isArraySchema: (schema: object) => boolean;
    isBinarySchema: (schema: object) => boolean;
    isBooleanSchema: (schema: object) => boolean;
    isByteSchema: (schema: object) => boolean;
    isDateSchema: (schema: object) => boolean;
    isDateTimeSchema: (schema: object) => boolean;
    isDoubleSchema: (schema: object) => boolean;
    isEnumerationSchema: (schema: object) => boolean;
    isFloatSchema: (schema: object) => boolean;
    isInt32Schema: (schema: object) => boolean;
    isInt64Schema: (schema: object) => boolean;
    isIntegerSchema: (schema: object) => boolean;
    isNumberSchema: (schema: object) => boolean;
    isObjectSchema: (schema: object) => boolean;
    isPrimitiveSchema: (schema: object) => boolean;
    isStringSchema: (schema: object) => boolean;
    schemaIsOfType: (schema: object, type: string) => boolean;
    collectFromComposedSchemas: typeof import("./utils/collect-from-composed-schemas.js").default;
    getExamplesForSchema: typeof import("./utils/get-examples-for-schema.js").default;
    getPropertyNamesForSchema: typeof import("./utils/get-property-names-for-schema.js").default;
};
export default _default;
export const collectFromComposedSchemas: typeof import("./utils/collect-from-composed-schemas.js").default;
export const getExamplesForSchema: typeof import("./utils/get-examples-for-schema.js").default;
export const getPropertyNamesForSchema: typeof import("./utils/get-property-names-for-schema.js").default;
export const getSchemaType: (schema: object) => symbol;
export const SchemaType: {
    ARRAY: symbol;
    BINARY: symbol;
    BOOLEAN: symbol;
    BYTE: symbol;
    DATE: symbol;
    DATE_TIME: symbol;
    DOUBLE: symbol;
    ENUMERATION: symbol;
    FLOAT: symbol;
    INT32: symbol;
    INT64: symbol;
    INTEGER: symbol;
    NUMBER: symbol;
    OBJECT: symbol;
    STRING: symbol;
    UNKNOWN: symbol;
};
export const isArraySchema: (schema: object) => boolean;
export const isBinarySchema: (schema: object) => boolean;
export const isBooleanSchema: (schema: object) => boolean;
export const isByteSchema: (schema: object) => boolean;
export const isDateSchema: (schema: object) => boolean;
export const isDateTimeSchema: (schema: object) => boolean;
export const isDoubleSchema: (schema: object) => boolean;
export const isEnumerationSchema: (schema: object) => boolean;
export const isFloatSchema: (schema: object) => boolean;
export const isInt32Schema: (schema: object) => boolean;
export const isInt64Schema: (schema: object) => boolean;
export const isIntegerSchema: (schema: object) => boolean;
export const isNumberSchema: (schema: object) => boolean;
export const isObjectSchema: (schema: object) => boolean;
export const isPrimitiveSchema: (schema: object) => boolean;
export const isStringSchema: (schema: object) => boolean;
export const schemaIsOfType: (schema: object, type: string) => boolean;
export const isObject: typeof import("./utils/is-object.js").default;
export const schemaHasConstraint: typeof import("./utils/schema-has-constraint.js").default;
export const schemaHasProperty: typeof import("./utils/schema-has-property.js").default;
export const schemaLooselyHasConstraint: typeof import("./utils/schema-loosely-has-constraint.js").default;
export const schemaRequiresProperty: typeof import("./utils/schema-requires-property.js").default;
export const getNodes: (context: object) => object;
export const getResolvedSpec: (context: object) => object;
export const getUnresolvedSpec: (context: object) => object;
export const validateComposedSchemas: typeof import("./utils/validate-composed-schemas.js").default;
export const validateNestedSchemas: typeof import("./utils/validate-nested-schemas.js").default;
export const validateSubschemas: typeof import("./utils/validate-subschemas.js").default;
export { collections };
import collections from './collections/index.js';
//# sourceMappingURL=index.d.ts.map